First try to add support for epub, tests are still pending, stuck trying to add the gem into the classpath, added manually ascii doctor j epub as it seems that the asciidoctorj does not include the epub jar yet
org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor/epub3
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1057)
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85)
	at RUBY.<main>(<script>:2)